version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-candidature
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: olivier
      POSTGRES_PASSWORD: olivier
      POSTGRES_DB: candidature
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - candidature-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - candidature-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - candidature-network

volumes:
  postgres-data:

networks:
  candidature-network:
