spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candidature
    username: olivier
    password: olivier
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true
    contexts: production

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
